# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fb4a74862d268bc2ebfa7cec44a4592592797fda1a1877376410f5afb34ce899460d166f5ee27bf81d5e5346945f21ae16fa31c1d6d5857368f6d836d7852a8

test:
  secret_key_base: 9cf08fd5de44b0e50334aa19efedfae587b2168a6b4bfe74b1260df0c0fa25356cc98fd910c11f691949a4a51cfce2c6a50076ff798d407475b607e107af663f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
